configure docker-compose.yml for Docker Swarm
7even/microservices pull request #6
Opened 2017-11-19 21:12 UTC by 7even

Д/з №27 в базовом объёме.

2017-12-03 12:29 UTC, vitkhab requested changes
7-8 ноября образ  prom/prometheus обновился до версии v2.0.0 и наш набор правил устарел. Это приводит к падению контейнера. Прошу решить данную проблему.

Добавь, пожалуйста, в .env.example нужные переменные.

И прошу добавить в README описание необходимых условий для запуска приложения.

2017-12-03 12:29 UTC, vitkhab commented on docker-compose.yml
> +      - ${UI_PORT}:9292/tcp
Переменная отсутствует в .env.example

2017-12-03 12:29 UTC, vitkhab commented on docker-compose.yml
> +    image: mongo:${MONGO_VERSION}
Переменная ${MONGO_VERSION} отсутствует в .env.example

2017-12-03 12:29 UTC, vitkhab commented on docker-compose.yml
> +          - node.labels.reliability == high
Можно указать в README о необходимости иметь в кластере ноду с label'ом `reliability == high` и других необходимых условиях запуска (если они есть)

2017-12-04 21:19 UTC, 7even commented
@vitkhab готово. Добавил переменные в `.env.example`, обновился до prometheus 2.0 и поправил readme.

2017-12-12 23:06 UTC, vitkhab approved these changes
Выглядит все хорошо. Спасибо за изменения!

2017-12-12 23:10 UTC, merged